services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mytodo-app
    container_name: mytodo-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mytodo-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mytodo
      - DB_USERNAME=root
      - DB_PASSWORD=root

  web:
    image: nginx:alpine
    container_name: mytodo-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mytodo-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mytodo-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mytodo
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mytodo-network

networks:
  mytodo-network:
    driver: bridge

volumes:
  dbdata:
